// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHy31fjCEgtgHgFwSTGw8QYLXkFgoN3E',
    appId: '1:1008027070417:web:3b373f37e7284bdf447af0',
    messagingSenderId: '1008027070417',
    projectId: 'scan-ki',
    authDomain: 'scan-ki.firebaseapp.com',
    storageBucket: 'scan-ki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoF64IBQwUQJ6sqmDmSm9Mb22rt1f9aCI',
    appId: '1:1008027070417:android:5da75af9be07d177447af0',
    messagingSenderId: '1008027070417',
    projectId: 'scan-ki',
    storageBucket: 'scan-ki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwQ9iTiL4qZGx1KBPTSNiSgpHFzsp5IA4',
    appId: '1:1008027070417:ios:bae7712064be426e447af0',
    messagingSenderId: '1008027070417',
    projectId: 'scan-ki',
    storageBucket: 'scan-ki.appspot.com',
    iosBundleId: 'com.example.qrcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwQ9iTiL4qZGx1KBPTSNiSgpHFzsp5IA4',
    appId: '1:1008027070417:ios:44213d2cefaf5617447af0',
    messagingSenderId: '1008027070417',
    projectId: 'scan-ki',
    storageBucket: 'scan-ki.appspot.com',
    iosBundleId: 'com.example.qrcode.RunnerTests',
  );
}
